### ISSUE TITLE
Why payment in amazone-clone can be used?

### ISSUE THREAD

**Issue by PeaceAntoHim** [MartsTech/amazon-clone#96]
Hi MartsTect I have a question why if I confirm order in Amazone-clone will come on stage like this "Please update your shipping details"

**Comment by MartsTech** [comment]
Sorry for the late replay, but for some reason I've completely missed this issue.

User details are required for any order and when you create a new account you should be redirect to the [welcome](https://amazon-clone-martstech.vercel.app/auth/welcome) page. There you can add your profile info.

If it does not redirect you automatically, please go to /auth/welcome/ from the base url. I will plan a fix for this.

Thank you for reporting this issue!
